### ISSUE TITLE
Downloaded zip file is empty

### ISSUE THREAD

**Issue by syntheticperson** [AndreyGermanov/image_grabber#1]
Great tutorial! But after selecting the images I want to download, the resulting zip file is empty! How do I fix this?

**Comment by AndreyGermanov** [comment]
Could you share links to the pages from which you tried to select and download images?

**Comment by syntheticperson** [comment]
Hi @AndreyGermanov, thanks for your reply.
One example is this webpage:
https://en.wikipedia.org/wiki/Cat
I tried selecting the first 2 cat images and then tried downloading the zip file.
The resulting zip file only consists of 8 bytes and is therefore empty.
<img width="1187" alt="Screen Shot 2023-01-07 at 10 04 48 AM" src="https://user-images.githubusercontent.com/119148/211164489-2714e5eb-db3c-4ca9-8f20-0c5bacbfae96.png">

**Comment by AndreyGermanov** [comment]
Hi @syntheticperson!

Thank you for your attention to this problem. 

I've checked the page you shared but could not reproduce this bug. Images in Zip archive downloaded successfully on my end, using last code from this repository ([images (8).zip](https://github.com/AndreyGermanov/image_grabber/files/10366967/images.8.zip)).

Please, compare the code you use with the code in this repository. Recently, I updated the code, because some Google API functions, that previously used in this extension became deprecated.

in particular, check the page.js file: https://github.com/AndreyGermanov/image_grabber/blob/main/page.js, especially functions createArchive and downloadArchive. Perhaps something does not match.

If it does not help, please, let me know which Google Chrome version and operating system did you use to reproduce this bug and I will check further.

**Comment by syntheticperson** [comment]
Strangely, this started working again for me.
Thanks
